config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  get "/logout", to: "sessions#destroy", as: :logout
 
  resources :users, only: [:index, :new, :create, :show, :edit, :destroy] 
  resources :sessions, only: [:new, :create, :destroy]
  resources :students, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :instructors, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :cohorts, only: [:index, :new, :create, :show, :edit, :destroy, :update] do
    resources :courses, only: [:index, :new, :show, :edit, :create, :destroy, :update]
    
    

  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :students, dependent: :destroy
  has_many :courses, dependent: :destroy
  has_one :instructor, dependent: :destroy
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :cohort
end

app/models/instructor.rb
class Instructor < ApplicationRecord
    belongs_to :cohort
    validates :age, numericality: {less_than: 150}
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :cohort
    validates :age, numericality: {less_than: 150}

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def edit
    @cohort = Cohort.find(params[:id])
    @cohorts = Cohort.all
  end

  def show
    @cohort = Cohort.find(params[:id])
  end

  def new
    @cohort = Cohort.new

  end

  def create
    @cohort = Cohort.new(cohort_params)
    if @cohort.valid?
      @cohort.save
      redirect_to "/cohorts/#{@cohort.id}"
    else 
      p @cohort.errors.messages
      render 'new'
    end
  end
  def index
    @cohorts = Cohort.all
    # @cohort = Cohort.find(params[:cohort_id])
  end

  def update 
    @cohort = Cohort.find(params[:id])
    if @cohort.update(cohort_params[:id])
      redirect_to @cohort, notice: "Cohort Updated"
    end
  end

  def destroy 
    @cohort = Cohort.find(params[:id])
    @cohort.destroy
    respond_to do |format|
      format.html { redirect_to cohorts_path }
      format.json { head :no_content }
      format.js { render :layout => false }
    end
  end
    



  private
  def cohort_params
    params.require(:cohort).permit(:name, :start_date, :end_date)
  end
   
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def edit
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
    @cohort = Cohort.find(params[:cohort_id])

  end

  def create
    @course = Course.new(course_params)
    @cohort_id = params[:cohort_id]
    @course_id = params[:course_id]
    @course.cohort_id = params[:cohort_id]
    if @course.valid?
      @course.save
      redirect_to "/cohorts/#{@cohort_id}/courses/#{@course_id}"
    else 
      p @course.errors.messages
      render 'new'
    end
  end

  
 

  def index
    @courses = Course.all
    @cohort = Cohort.find(params[:cohort_id])

  end


  private
  def course_params
  params.require(:course).permit(:name, :start_time, :end_time, :cohort_id, :course_id)
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  
    def show
      @instructor = Instructor.find(params[:id])
  
    end
  
    def new
     @instructor = Instructor.new
     @cohorts = Cohort.all
    end
  
    def create 
      @instructor = Instructor.new(instructor_params)
      if @instructor.valid?
        @instructor.save
        redirect_to "/instructors/#{@instructor.id}"
      else
        @errors = @instrcutor.errors.full_messages
        @cohorts = Cohort.all
        render 'new'
      end
    end
  
  def edit 
    @instructor = Instructor.find(params[:id])
    @cohorts = Cohort.all
  end 
    
  
    def index
      @instructors = Instructor.all
  
    end

    def update 
      @instructor = Instructor.find(params[:id])
      if @instructor.update(instructor_params)
        redirect_to @instructor, notice: 'Instructor Updated.'
    end
  end

  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_path }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end
  
  
  
    private
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end


    def instructor_params
      params.require(:instructor).permit(:first_name, :last_name, :email, :age, :salary, :level_of_education, :cohort_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        if session[:user_id] != nil
            redirect_to "/users/"+ session[:user_id].to_s
        end
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to "/users/"+@user.id.to_s
        else 
            @error = "Email or Password is Incorrect"
            render "new"

        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to new_session_path
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
    def show
      @student = Student.find(params[:id])
  
    end
  
    def new
     @student = Student.new
     @cohorts = Cohort.all
    end
  
    def create 
      @student = Student.new(student_params)
      if @student.valid?
        @student.save
        redirect_to "/students/#{@student.id}"
      else
        @errors = @student.errors.full_messages
        @cohorts = Cohort.all
        render 'new'
      end
    end

    def edit
      @student = Student.find(params[:id])
      @cohorts = Cohort.all
    end
  
    def index
      @students = Student.all
  
    end

    def update
      @student = Student.find(params[:id])
      if @student.update(student_params)
        redirect_to @student, notice: 'Student Updated'
      end
    end

    def destroy 
      @student = Student.find(params[:id])
      @student.destroy
      respond_to do |format|
        format.html { redirect_to students_path }
        format.json { head :no_content }
        format.js { render :layout => false }
      end
    end

  
  
    private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:role, :first_name, :last_name, :email, :age,:level_of_education, :cohort_id)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

  end

  def new
   @user = User.new
   
  end

  def create 
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to "/users/#{@user.id}"
    else
      @errors = @user.errors.full_messages
     
      render 'new'
    end
  end

  

  def index
    @users = User.all

  end

  def edit
    
    
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    
    respond_to do |format|
      format.html {redirect_to users_url}
      format.json {head :no_content}
      format.js {render :layout=>false}
    end
  end


  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find(session[:user_id])
    end
    def logged_in?
        !!session[:user_id]
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cohorts/destroy.js.erb
$('.delete_cohort').bind('ajax:success', function() {  
        $(this).closest('.wrapper').fadeOut();
     console.log('this worked')
});

app/views/cohorts/edit.html.erb
<h1>Cohorts#edit</h1>
<div class="card">
<h1>New Cohort</h1>
<div class="container">
<%= form_for @cohort, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    <div class="name">
    <%= f.label :name%><br>
    <%= f.text_field :name %>
    </div>
    <div class= "start">
    <%= f.label :start_date%><br>
    <%= f.date_field :start_date %>
    </div>
    <div class="end">
    <%= f.label :end_date%><br>
    <%= f.date_field :end_date %>
    </div>
    
   

<div class="submit">
    <%= f.submit "Create" %>
    </div>
  <% end %>
</div>
</div>

app/views/cohorts/index.html.erb
<div class="card">
<% @cohorts.each do |cohort| %>
    <div class="wrapper"> 
    <div class="card-header">
    <%= link_to cohort.name, cohort_path(cohort.id) %>
    </div>
    <div>
    
   
    <%= link_to 'Delete', cohort, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_cohort' %> 
    </div>

    </div>
    <% end %>
    </div>
   

app/views/cohorts/new.html.erb
<link href="https://fonts.googleapis.com/css?family=Alegreya+SC|Rasa" rel="stylesheet">
<div class="background">
</div>
<div class="card">
<h1>New Cohort</h1>
<div class="container">
<%= form_for @cohort, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    <div class="name">
    <%= f.label :name%><br>
    <%= f.text_field :name %>
    </div>
    <div class= "start">
    <%= f.label :start_date%><br>
    <%= f.date_field :start_date %>
    </div>
    <div class="end">
    <%= f.label :end_date%><br>
    <%= f.date_field :end_date %>
    </div>
    
   

<div class="submit">
    <%= f.submit "Create" %>
    </div>
  <% end %>
</div>
</div>

app/views/cohorts/show.html.erb
<h1></h1>




<div class="card">
  <h1 class="card-header"><%= @cohort.name %></h1>
  <div class="card-body">
    <h2 class="card-title">Teacher: <%= @cohort.instructor.first_name%> <%= @cohort.instructor.last_name%></h2>
    
    <h5 class="card-title">Start Date: <%= @cohort.start_date %></h5>
    
    <h5 class="card-title">End Date: <%= @cohort.end_date %></h5>
    <%= link_to "courses",cohort_courses_path(@cohort.id) %>

  </div>
</div>

app/views/courses/edit.html.erb
<h1>Courses#edit</h1>
<p>Find me in app/views/courses/edit.html.erb</p>

app/views/courses/index.html.erb
<div class="card">
<h1>Courses</h1>
<% @cohort.courses.each do |course| %>
 
  <h5 class="card-header"> <%= link_to course.name, cohort_course_path(@cohort.id, course.id)  %>
  </h5>
 
  </p>
  
 
  </div>
</div>

<% end %>
<p class="card-header"> <%= link_to "New Course", new_cohort_course_path(@cohort.id) %> 
</div>

app/views/courses/new.html.erb
<div class="container">
<%= form_for @course, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
   

    <div class="card">
    <div class="card-header"><h1>Add Courses</h1>
    </div>
    <div class="card-body">
      <h6 class="card-title"><%= f.label :name%></h6>
      <h6 class="card-title"><%= f.text_field :name %></h6>
      <h6 class="card-title"><%= f.label :start_time%></h6>
      <h6 class="card-title"><%= f.time_field :start_time %></h6>
      <h6 class="card-title"><%= f.label :end_time %></h6>
      <h6 class="card-title"><%= f.time_field :end_time %><br></h6>


    <div class="button">
      <%= f.submit "Add" %>
      </div>
    </div>
    <% end %>
  </div>




    
    
   

app/views/courses/show.html.erb
<div class="card">
<h1><%=@course.name%></h1>
<h2>Start Time: <%=@course.start_time%><h2>
<h2>End Time: <%=@course.end_time%><h2>
</div>

app/views/instructors/destroy.js.erb
$('.delete_instructor').bind('ajax:success', function() {  
        $(this).closest('.wrapper').fadeOut();
     console.log('this worked')
});  

app/views/instructors/edit.html.erb
<%= @instructor.first_name %>

<%= form_for @instructor, html: {class: "nifty_form"} do |f| %>
   
    <div class="firstname">
    <%= f.label :first_name%><br>
  <%= f.text_field :first_name %>
  </div>
  <div class="lastname">
  <%= f.label :last_name%><br>
  <%= f.text_field :last_name %>
  </div>
  <div class="email">
  <%=f.label :email%><br>
  <%= f.text_field :email %>
  </div>
  
  <div class="age">
  <%= f.label :age%><br>
  <%= f.number_field :age %>
  </div>

  <div class="salary">
  <%= f.label :salary%><br>
  <%= f.number_field :salary %>
  </div>
  
  
  <div class="education">
  <%= f.label :level_of_education%><br>
  <%= f.select(:level_of_education) do %>
      <% [['High School ', 'High School'], ['College', 'College'], ['Masters', 'Masters'], ['PHD', 'PHD']].each do |c| -%>
        <%= content_tag(:option, c.first, value: c.last) %>
      <% end %>
    <% end %>
    </div>

    <div class="cohortopt">
  <%= f.label :cohort%><br>
  <%= f.select(:cohort_id) do %>
    <% @cohorts.each do |cohort| %>      
        <%= content_tag(:option, cohort.name, value: cohort.id) %>
      <% end %>
    <% end %>
    </div>
 

<div class="button">
  <%= f.submit "Create" %>
  </div>
<% end %>
</div>

app/views/instructors/index.html.erb
<h1>Instructors</h1>

<%= link_to "New Instructor", new_instructor_path %>
<div class="card">
<% @instructors.each do |instructor| %>
    <div class="wrapper">
    <h5 class="card-title">
    <%=link_to instructor.first_name + ' ' + instructor.last_name, instructor_path(instructor.id) %>
    </h5>
    
   
    <%=link_to "Edit", edit_instructor_path(instructor) %>
    <%= link_to 'Delete', instructor, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_instructor' %> 
    </div>
 
    <% end %>
 

app/views/instructors/new.html.erb
<h2>New Instructor</h2>
<%= form_for @instructor, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
   
  <div class="card">
  <div class="card-header">
    New Instructor
  </div>
  <li class="list-group-item">
      <%= f.label :first_name%><br>
    <%= f.text_field :first_name %>
    </li>
    <li class="list-group-item">
    <%= f.label :last_name%><br>
    <%= f.text_field :last_name %>
    </li>
    <li class="list-group-item">
    <%=f.label :email%><br>
    <%= f.text_field :email %>
    </li>
    
    <li class="list-group-item">
    <%= f.label :age%><br>
    <%= f.number_field :age %>
    </li>

    <li class="list-group-item">
    <%= f.label :salary%><br>
    <%= f.number_field :salary %>
    </li>
    
    
    <li class="list-group-item">
    <%= f.label :level_of_education%><br>
    <%= f.select(:level_of_education) do %>
        <% [['High School ', 'High School'], ['College', 'College'], ['Masters', 'Masters'], ['PHD', 'PHD']].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>
      </li>

      <li class="list-group-item">
    <%= f.label :cohort%><br>
    <%= f.select(:cohort_id) do %>
      <% @cohorts.each do |cohort| %>      
          <%= content_tag(:option, cohort.name, value: cohort.id) %>
        <% end %>
      <% end %>
      </li>
      </ul>
   

<div class="button">
    <%= f.submit "Create" %>
    </div>
  <% end %>
  </div>
 

app/views/instructors/show.html.erb
<div class="inst">
<div class="inst-title">Instructor</div>
<div class="name">Name: <%= @instructor.first_name + " " + @instructor.last_name %></div>
<div class="cohort">Cohort: <%= @instructor.cohort.name %></div>
<div class="inst-email"><%= @instructor.email %></div>
</div>

app/views/layouts/_navbar.html.erb
<% if logged_in? %>
<ul>
<li class="email">
<%= current_user.email %>
</li>
<li>
<%= link_to "cohorts", cohorts_path %>
</li>
<li>
<%= link_to "users", users_path %>
</li>
<li>
<%= link_to  "students", students_path %>
</li>
<li>
<%= link_to  "instructors", instructors_path %>
</li>
<li>
<%= link_to "log out", logout_path %>
</li>
<% else %>
<li>
<%= link_to "log in", new_session_path %>
</li>
<%end%>
</ul

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminPanel2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navbar" %>
    <%= yield %>
    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  </body>
</html>

app/views/students/destroy.js.erb
$('.delete_student').bind('ajax:success', function() {  
        $(this).closest('.delete-button').fadeOut();
     console.log('this worked')
}); 

app/views/students/edit.html.erb
<div class="card">
<div class="card-header"><h1>
Edit Student</h1>
</div>
<div class="userscontainer">
<%= form_for @student, html: {class: "nifty_form"} do |f| %>
    <div class="firstname">
      <%= f.label :first_name%><br>
    <%= f.text_field :first_name %>
    </div>
    <div class="lastname">
    <%= f.label :last_name%><br>
    <%= f.text_field :last_name %>
    </div>
    <div class="email">
    <%=f.label :email%><br>
    <%= f.text_field :email %>
    </div>
    
    <div class="age">
    <%= f.label :age%><br>
    <%= f.number_field :age %>
    </div>
    
    <div class="education">
    <%= f.label :level_of_education%><br>
    <%= f.select(:level_of_education) do %>
        <% [['High School ', 'High School'], ['College', 'College'], ['Masters', 'Masters'], ['PHD', 'PHD']].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>
      </div>

      <div class="cohortopt">
    <%= f.label :cohort%><br>
    <%= f.select(:cohort_id) do %>
      <% @cohorts.each do |cohort| %>      
          <%= content_tag(:option, cohort.name, value: cohort.id) %>
        <% end %>
      <% end %>
      </div>
   

<div class="button">
    <%= f.submit "Update" %>
    </div>
  <% end %>
  </div>
  </div>
</div>

app/views/students/index.html.erb
<h1>Students</h1>
<%= link_to "New Student", new_student_path %>
<div class="card">
<% @students.each do |student| %>
    <div class="delete-button">
    <h5 class="card-title">
    <%=link_to student.first_name + ' ' + student.last_name, student_path(student.id) %>
    </h5>
    <%=link_to "Edit", edit_student_path(student) %>
    <%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_student' %> 

    </div>
    <% end %>

app/views/students/new.html.erb
<link href="https://fonts.googleapis.com/css?family=Alegreya+SC|Rasa" rel="stylesheet">
<div class="background">
</div>
<div class="card">
<div class="card-header">
<h1>New Student</h1>
<% if @errors %>
<div class="errors">
<% @errors.each do |error| %>
  <p><%= error %></p>
  <% end %>
  </div>
<% end %>
<div class="userscontainer">
<%= form_for @student, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
   
      <div class="firstname">
      <%= f.label :first_name%><br>
    <%= f.text_field :first_name %>
    </div>
    <div class="lastname">
    <%= f.label :last_name%><br>
    <%= f.text_field :last_name %>
    </div>
    <div class="email">
    <%=f.label :email%><br>
    <%= f.text_field :email %>
    </div>
    
    <div class="age">
    <%= f.label :age%><br>
    <%= f.number_field :age %>
    </div>
    
    <div class="education">
    <%= f.label :level_of_education%><br>
    <%= f.select(:level_of_education) do %>
        <% [['High School ', 'High School'], ['College', 'College'], ['Masters', 'Masters'], ['PHD', 'PHD']].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>
      </div>

      <div class="cohortopt">
    <%= f.label :cohort%><br>
    <%= f.select(:cohort_id) do %>
      <% @cohorts.each do |cohort| %>      
          <%= content_tag(:option, cohort.name, value: cohort.id) %>
        <% end %>
      <% end %>
      </div>
   

<div class="button">
    <%= f.submit "Create" %>
    </div>
  <% end %>
  </div>
  </div>

app/views/students/show.html.erb
<div class="inst">
<div class="inst-title">Student</div>
<div class="name">Name: <%= @student.first_name + " " + @student.last_name %></div>
<div class="cohort">Cohort: <%= @student.cohort.name %></div>
<div class="inst-email"><%= @student.email %></div>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Admin List</h1>
<%=link_to "New User", new_user_path %>

<% @users.each do |user| %>
    <div class="card-header">
    <%=link_to user.first_name + ' ' + user.last_name, user_path(user.id) %>
    </div>
    <% end %>

    

app/views/users/new.html.erb
<link href="https://fonts.googleapis.com/css?family=Alegreya+SC|Rasa" rel="stylesheet">
<div class="background">
</div>
<div class="card">
<h1>New Admin</h1>
<% if @errors %>
<div class="errors">
<% @errors.each do |error| %>
  <p><%= error %></p>
  <% end %>
  </div>
<% end %>
<div class="card-header">
<%= form_for @user, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    
      <div class="firstname">
      <%= f.label :first_name%><br>
    <%= f.text_field :first_name %>
    </div>
    <div class="lastname">
    <%= f.label :last_name%><br>
    <%= f.text_field :last_name %>
    </div>
    <div class="email">
    <%=f.label :email%><br>
    <%= f.text_field :email %>
    </div>
    <div class="password">
    <%=f.label :password%><br>
    <%= f.password_field :password %>
    </div>
    <div class="confirm_password">
    <%=f.label :password_confirmation%><br>
    <%= f.password_field :password_confirmation %>
    </div>
   

<div class="button">
    <%= f.submit "Create" %>
    </div>
  <% end %>
  </div>
  </div>

app/views/users/show.html.erb
<div class="admin-title">
<h3>Admin User</h3>
</div>
<div class="user-title">
<h2><%= @user.first_name + " " + @user.last_name %></h2>
</div>